[project]
name = "hbr-autobeat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.0.0",
    "pyautogui>=0.9.54",
    "pyinstaller>=6.11.1",
    "pynput>=1.7.7",
    "pywin32>=308",
    "pyyaml>=6.0.1",
]

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503", "E501"]

[tool.mypy]
python_version = 3.13
ignore_missing_imports = true
strict = false
